name: Build & Publish Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - '*'

jobs:
  docker-jammy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build if changed
      run: |
        if ! git diff --exit-code origin/main -- Tools/setup/ubuntu.sh Tools/docker/Dockerfile-jammy; then
          (cd Tools/docker && docker build . -t px4-dev -f Dockerfile-jammy --build-arg git_ref=${{ github.sha }})
          export SRC_DIR="/PX4-Autopilot"
          sudo docker run --rm -w "${SRC_DIR}" --volume=$(pwd):${SRC_DIR}:rw px4-dev make px4_fmu-v2
        fi
