name: Build & Publish Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - '*'

jobs:
  docker-jammy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build if changed
      run: |
        if ! git diff --exit-code origin/main Tools/setup/ubuntu.sh Tools/docker/Dockerfile-jammy; then
          (cd Tools/docker && docker build . -t px4-dev -f Dockerfile-jammy)
          PX4_DOCKER_REPO=px4-dev Tools/docker_run.sh make px4_fmu-v2
        fi
